config/routes.rb
RailsDevisePundit::Application.routes.draw do
  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contacts'

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :publications
end

app/models/publication.rb
class Publication < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "Access denied."
    redirect_to (request.referrer || root_path)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
	def new
	end
 def create
  @publication = Publication.new(publication_params)
 
  @publication.save
  redirect_to @publication
  end
def show
  @publication = Publication.find(params[:id])
end
def index
  @publication = Publication.all
end
def destroy
  #@publication = Publication.destroy
    @publication = Publication.find(params[:id])
    @publication.destroy
    redirect_to(:back)
    flash[:error] = "Post was destroyed!"
end
private
  def publication_params
    params.require(:publication).permit(:title, :text)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation, :avatar, :avatar_cache)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :avatar, :avatar_cache)}
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def contacts
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized, except: [:show]

  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/home/index.html.erb
<div class="row">
<div class="col-md-6 col-sm-6"><% @users.each do |user| %>
  <div><div class="userdiv" style="border-bottom-style: dashed; border-width: 5px; width: 50%; padding: 20px;"> <p><%= image_tag(user.avatar, :align => 'left') if user.avatar? %></p>
    <p>User: <%= user.name %>
    
    <p><%=link_to user.email, user %></p>
    <p>Role: <%= user.role unless user.role.nil? %></p>
</div></div>
  <% end %></div>

</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class="divider-vertical"></li>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'get' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
  <li class="divider-vertical"></li>
  <li><%= link_to 'Projects', root_path %></li>
 <% if current_user.admin? %>
 ADMINЪ
<% end %>
<% end %>
<li><%= link_to 'About', static_pages_about_path %><li>
	<li><%= link_to 'Contacts', static_pages_contacts_path %><li>
		<li><%= link_to 'Index', static_pages_index_path %><li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <link rel="stylesheet" type="text/css" href='http://fonts.googleapis.com/css?family=Ubuntu:400,700,500,400italic|Ubuntu+Mono:400,400italic,700&subset=cyrillic-ext,latin-ext,latin'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise Pundit" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Pundit" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/publications/index.html.erb
<div class="row">
  <div class="col-md-4 col-xs-12"><h1>Listing articles: <%= @publication.length %>
  <p><%= link_to new_publication_path, class: "btn btn-success" do %>
    <i class="glyphicon glyphicon-plus-sign"> New Publication</i>
<% end %></p></h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @publication.each do |publication| %>
    <tr>
      <td width="25%"><%= publication.title %></td>
      <td width="50%"><%= publication.text %></td>
      
      <td width="25%"><%= link_to publication, class: "btn btn-danger btn-sm", :method => :delete, :confirm => "Are you sure?" do %>
        <i class="glyphicon glyphicon-remove">
        <% end %></td>
    </tr>
  <% end %>
</table>
</div>
<div class="col-md-4"></div><div class="col-md-4 col-xs-12" style="padding-top: 20px;">
   <% @publication.each do |publication| %>
    <div class="аа" style="border-bottom-width: 5px; border-style: dashed; padding">
       <div class="zz" style="background: rgba(255,255,255,0.2); padding: 10px;">
    <h3><%= publication.title %></h3>
    <p><%= publication.text %></p>
  </div>
    </div>
    <% end %>
    
  </div>
 
</div></div>
</div>

app/views/publications/new.html.erb
<%= form_for :publication, url: publications_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit "save", :class => "btn btn-success" %>
    
  </p>
<% end %>

app/views/publications/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @publication.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @publication.text %>
</p><p>

<%= link_to 'Back', publications_path %><p>
  

app/views/static_pages/about.html.erb
<div class="row" style "height: 50%;">
<div class="span4"></div><div class="span4"><div id="Mycarousel" class="carousel slide carousel-fade" style="height: 100%; width: 100%; padding-top: 0px;">
  <ol class="carousel-indicators">
    <li data-target="#slide" data-slide-to="0" class="active"></li>
    <li data-target="#slide" data-slide-to="1"></li>
    <li data-target="#slide" data-slide-to="2"></li>
    <li data-target="#slide" data-slide-to="3"></li>
    <li data-target="#slide" data-slide-to="4"></li>
  </ol>

  
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
       <div class="carousel-caption">
    <h3>TITLE</h3>
    <p>Lorem ipsum dolor sid amed...</p>
  </div>
    </div>
    <div class="item">
        <div class="carousel-caption">
    <h3>TITLE</h3>
  </div>
    </div>
    <div class="item">
       <div class="carousel-caption">
    <h3>TITLE</h3>
    <p>Lorem ipsum dolor sid amed...</p>
  </div>
    </div>
    <div class="item"></div>
    <div class="item"></div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left " href="#Mycarousel" data-slide="prev">
    &lsaquo;</a>
  <a class="carousel-control right" href="#Mycarousel" data-slide="next">
     &rsaquo;</a>
</div></div>
</div>

app/views/static_pages/contacts.html.erb
<div class="row">
<div class="span4"></div><div class="span4"><div id="Mycarousel" class="carousel slide carousel-fade" style="height: 300px; width: 100%;">
  <ol class="carousel-indicators">
    <li data-target="#slide" data-slide-to="0" class="active"></li>
    <li data-target="#slide" data-slide-to="1"></li>
    <li data-target="#slide" data-slide-to="2"></li>
    <li data-target="#slide" data-slide-to="3"></li>
    <li data-target="#slide" data-slide-to="4"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
       <div class="carousel-caption">
    <h3>TITLE</h3>
    <p>Lorem ipsum dolor sid amed...</p>
  </div>
    </div>
    <div class="item">
        <div class="carousel-caption">
    <h3>TITLE</h3>
  </div>
    </div>
    <div class="item">
       <div class="carousel-caption">
    <h3>TITLE</h3>
    <p>Lorem ipsum dolor sid amed...</p>
  </div>
    </div>
    <div class="item"></div>
    <div class="item"></div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left " href="#Mycarousel" data-slide="prev">
    &lsaquo;</a>
  <a class="carousel-control right" href="#Mycarousel" data-slide="next">
     &rsaquo;</a>
</div></div>
</div>
<h1>StaticPages#contacts</h1>
<p>Find me in app/views/static_pages/contacts.html.erb</p>

app/views/static_pages/index.html.erb
<div class="row">
<div class="span4"></div><div class="span4"><div id="Mycarousel" class="carousel slide carousel-fade" style="height: 300px; width: 100%;">
  <ol class="carousel-indicators">
    <li data-target="#slide" data-slide-to="0" class="active"></li>
    <li data-target="#slide" data-slide-to="1"></li>
    <li data-target="#slide" data-slide-to="2"></li>
    <li data-target="#slide" data-slide-to="3"></li>
    <li data-target="#slide" data-slide-to="4"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
       <div class="carousel-caption">
    <h3>TITLE</h3>
    <p>Lorem ipsum dolor sid amed...</p>
  </div>
    </div>
    <div class="item">
        <div class="carousel-caption">
    <h3>TITLE</h3>
  </div>
    </div>
    <div class="item">
       <div class="carousel-caption">
    <h3>TITLE</h3>
    <p>Lorem ipsum dolor sid amed...</p>
  </div>
    </div>
    <div class="item"></div>
    <div class="item"></div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left " href="#Mycarousel" data-slide="prev">
    &lsaquo;</a>
  <a class="carousel-control right" href="#Mycarousel" data-slide="next">
     &rsaquo;</a>
</div></div>
</div>
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>